# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: froseai.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'froseai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfroseai.proto\"\x1f\n\x0b\x46\x65RoseAiMsg\x12\x10\n\x08messages\x18\x01 \x01(\x0c\x32\xa5\x01\n\x08\x46\x65RoseAi\x12%\n\x05Hello\x12\x0c.FeRoseAiMsg\x1a\x0c.FeRoseAiMsg\"\x00\x12$\n\x04Push\x12\x0c.FeRoseAiMsg\x1a\x0c.FeRoseAiMsg\"\x00\x12$\n\x04Pull\x12\x0c.FeRoseAiMsg\x1a\x0c.FeRoseAiMsg\"\x00\x12&\n\x06Status\x12\x0c.FeRoseAiMsg\x1a\x0c.FeRoseAiMsg\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'froseai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FEROSEAIMSG']._serialized_start=17
  _globals['_FEROSEAIMSG']._serialized_end=48
  _globals['_FEROSEAI']._serialized_start=51
  _globals['_FEROSEAI']._serialized_end=216
# @@protoc_insertion_point(module_scope)
