# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import froseai_pb2 as froseai__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in froseai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FeRoseAiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Hello = channel.unary_unary(
                '/FeRoseAi/Hello',
                request_serializer=froseai__pb2.FeRoseAiMsg.SerializeToString,
                response_deserializer=froseai__pb2.FeRoseAiMsg.FromString,
                _registered_method=True)
        self.Push = channel.unary_unary(
                '/FeRoseAi/Push',
                request_serializer=froseai__pb2.FeRoseAiMsg.SerializeToString,
                response_deserializer=froseai__pb2.FeRoseAiMsg.FromString,
                _registered_method=True)
        self.Pull = channel.unary_unary(
                '/FeRoseAi/Pull',
                request_serializer=froseai__pb2.FeRoseAiMsg.SerializeToString,
                response_deserializer=froseai__pb2.FeRoseAiMsg.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/FeRoseAi/Status',
                request_serializer=froseai__pb2.FeRoseAiMsg.SerializeToString,
                response_deserializer=froseai__pb2.FeRoseAiMsg.FromString,
                _registered_method=True)


class FeRoseAiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Hello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Push(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pull(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeRoseAiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Hello': grpc.unary_unary_rpc_method_handler(
                    servicer.Hello,
                    request_deserializer=froseai__pb2.FeRoseAiMsg.FromString,
                    response_serializer=froseai__pb2.FeRoseAiMsg.SerializeToString,
            ),
            'Push': grpc.unary_unary_rpc_method_handler(
                    servicer.Push,
                    request_deserializer=froseai__pb2.FeRoseAiMsg.FromString,
                    response_serializer=froseai__pb2.FeRoseAiMsg.SerializeToString,
            ),
            'Pull': grpc.unary_unary_rpc_method_handler(
                    servicer.Pull,
                    request_deserializer=froseai__pb2.FeRoseAiMsg.FromString,
                    response_serializer=froseai__pb2.FeRoseAiMsg.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=froseai__pb2.FeRoseAiMsg.FromString,
                    response_serializer=froseai__pb2.FeRoseAiMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FeRoseAi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FeRoseAi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FeRoseAi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Hello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FeRoseAi/Hello',
            froseai__pb2.FeRoseAiMsg.SerializeToString,
            froseai__pb2.FeRoseAiMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Push(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FeRoseAi/Push',
            froseai__pb2.FeRoseAiMsg.SerializeToString,
            froseai__pb2.FeRoseAiMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pull(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FeRoseAi/Pull',
            froseai__pb2.FeRoseAiMsg.SerializeToString,
            froseai__pb2.FeRoseAiMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FeRoseAi/Status',
            froseai__pb2.FeRoseAiMsg.SerializeToString,
            froseai__pb2.FeRoseAiMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
